title: Oceans are Life
description: Learning about our oceans
baseurl: "/Oceans-are-life"
url: "https://rj252525.github.io"

# Build settings
markdown: kramdown
permalink: pretty
remote_theme: pages-themes/cayman@v0.2.0