title: Your Site Title
description: Your site description
baseurl: ""  # leave empty if using username.github.io
url: "https://rj252525.github.io"

# Build settings
markdown: kramdownremote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
